name: Beets Music Organizer
version: 1.0.0
slug: beets
description: A Home Assistant Add-On that uses beets to organize music files and enrich metadata.
options:
  music_input_dir: /data/input
  music_output_dir: /data/output
  import_timeout: 60
  beets_import_args: --move
schema:
  music_input_dir: str
  music_output_dir: str
  import_timeout: int
  beets_import_args: str
map:
  - media:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
